"""Command line entrypoint.

    python -m fantasyedge auth     --provider yahoo
    python -m fantasyedge discover --provider espn
    python -m fantasyedge pull     --provider espn --league 123456 --seasons 2022-2026
    python -m fantasyedge pull     --provider manual --draft draft.txt --standings st.txt
    python -m fantasyedge adp-load --season 2026 --csv adp.csv
    python -m fantasyedge analyze
    python -m fantasyedge report   --out report.html
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import pathlib
import time
import sys
import tomllib

from . import analytics, doctor as doc, report
from .providers import base as pbase
from .providers.espn import EspnProvider      # noqa: F401  registers "espn"
from .providers.sleeper import SleeperProvider  # noqa: F401  registers "sleeper"
from .providers.manual import ManualProvider  # noqa: F401  registers "manual"
from .providers.yahoo import YahooAuth, YahooProvider  # noqa: F401  registers "yahoo"
from .store import Store

DEFAULT_CONFIG = pathlib.Path("config/league.toml")


def load_config(path: pathlib.Path = DEFAULT_CONFIG) -> dict:
    if not path.exists():
        return {}
    with path.open("rb") as fh:
        return tomllib.load(fh)


def parse_seasons(spec: str) -> list[int]:
    """Accepts 2024, 2022-2026, or 2022,2024,2026."""
    out: set[int] = set()
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if "-" in chunk:
            a, b = chunk.split("-", 1)
            out.update(range(int(a), int(b) + 1))
        elif chunk:
            out.add(int(chunk))
    return sorted(out)


def emit(args, payload: dict, human: str) -> None:
    """One output path, two renderings. Agents read JSON, humans read prose."""
    if getattr(args, "json", False):
        print(json.dumps(payload, indent=2))
    else:
        print(human)


def _scope(store: Store, cfg: dict, args) -> tuple[str, str]:
    provider = getattr(args, "provider", None) or cfg.get("league", {}).get("provider")
    league = getattr(args, "league", None) or cfg.get("league", {}).get("league_id")
    if not (provider and league):
        rows = store.seasons()
        if not rows:
            sys.exit("Nothing loaded yet. Run `pull` first.")
        provider, league = rows[0]["provider"], rows[0]["league_id"]
    return str(provider), str(league)


# ───────────────────────────── commands ──────────────────────────────

def cmd_setup(args, cfg) -> None:
    """Write config/league.toml without an interactive prompt.

    Agent-safe: every value comes from a flag, nothing blocks on stdin.
    """
    path = pathlib.Path(args.config)
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = load_config(path)
    league = existing.get("league", {}) or {}
    league["provider"] = args.provider or league.get("provider", "espn")
    if args.league:
        league["league_id"] = str(args.league)
    if args.teams:
        league["teams"] = args.teams
    league.setdefault("league_id", "")
    league.setdefault("teams", 10)
    league.setdefault("name", "")

    roster = existing.get("roster") or {
        "QB": 1, "RB": 2, "WR": 2, "TE": 1, "FLEX": 1, "K": 1, "DEF": 1,
        "bench": 6, "flex_eligible": ["RB", "WR", "TE"],
    }
    scoring = existing.get("scoring") or {
        "reception": 0.5, "pass_yard": 0.04, "rush_yard": 0.1,
        "rec_yard": 0.1, "return_yard": 0.04, "touchdown": 6.0,
    }
    analysis = existing.get("analysis") or {
        "playoff_start_week": 15, "early_draft_rounds": 5,
    }

    def dump(table: str, d: dict) -> str:
        out = [f"[{table}]"]
        for k, v in d.items():
            if isinstance(v, str):
                out.append(f'{k} = "{v}"')
            elif isinstance(v, bool):
                out.append(f"{k} = {str(v).lower()}")
            elif isinstance(v, list):
                out.append(f"{k} = [" + ", ".join(f'"{x}"' for x in v) + "]")
            else:
                out.append(f"{k} = {v}")
        return "\n".join(out)

    path.write_text("\n\n".join([
        "# Generated by `fantasyedge setup`. Safe to hand-edit.",
        dump("league", league), dump("roster", roster),
        dump("scoring", scoring), dump("analysis", analysis),
    ]) + "\n")
    emit(args, {"wrote": str(path), "league": league}, f"Wrote {path}")


def cmd_doctor(args, cfg) -> None:
    d = doc.diagnose(args.db, cfg, pathlib.Path(args.config))
    if args.json:
        print(json.dumps(d.to_dict(), indent=2))
    else:
        print(doc.render_text(d))
    sys.exit(d.exit_code)

def cmd_auth(args, cfg) -> None:
    if args.provider != "yahoo":
        print(f"{args.provider} does not use OAuth.")
        if args.provider == "espn":
            print("Set ESPN_S2 and ESPN_SWID from your browser cookies instead.")
        return
    auth = YahooAuth()
    if not auth.client_id:
        sys.exit(doc.EXIT_AUTH)

    # --local runs the RFC 8252 loopback flow: bind 127.0.0.1 on a kernel-chosen
    # port, open the browser, catch the redirect. It is opt-in rather than the
    # default because it only works if the loopback URI is what is registered
    # with the provider, and Yahoo's app form currently insists on https - so
    # the copy-the-code path stays exactly as it was for everybody else.
    if getattr(args, "local", False):
        from . import oauth as oa
        from . import tokens as tk

        cfg_p = oa.get_provider_config("yahoo")
        creds = oa.credentials_from_env(cfg_p)
        tokens = oa.run_loopback_flow(cfg_p, creds)
        path = tk.save_cli_tokens(tokens, "yahoo")
        emit(args, {"saved": str(path), "scope": tokens.scope},
             f"Saved to {path} (mode 600). Refresh is automatic from here.")
        return

    # --url prints the authorize URL and exits. --code completes the exchange.
    # Neither blocks on stdin, so an agent can drive both halves and hand the
    # URL to a human in between. Interactive input is the fallback, not the path.
    if args.url or (not args.code and not sys.stdin.isatty()):
        emit(args, {"authorize_url": auth.authorize_url(),
                    "next": "python3 -m fantasyedge auth --provider yahoo --code <CODE>"},
             "Open this URL, approve, then rerun with --code <CODE>:\n\n  "
             + auth.authorize_url())
        return

    code = args.code or input("code: ").strip()
    auth.exchange(code)
    emit(args, {"saved": str(auth.token_path)},
         f"Saved to {auth.token_path} (mode 600). Refresh is automatic from here.")


def cmd_discover(args, cfg) -> None:
    kwargs = {}
    if args.provider == "manual":
        kwargs = {"draft_file": args.draft, "standings_file": args.standings}
    provider = pbase.get_provider(args.provider, **kwargs)
    for ref in provider.discover():
        seasons = ", ".join(map(str, ref.seasons)) or "unknown"
        print(f"{ref.provider}  league {ref.league_id}  {ref.name}")
        print(f"  seasons: {seasons}")


def cmd_pull(args, cfg) -> None:
    store = Store(args.db)
    kwargs = {}
    if args.provider == "manual":
        kwargs = {
            "draft_file": args.draft,
            "standings_file": args.standings,
            "league_id": args.league or "manual",
            "teams": args.teams or cfg.get("league", {}).get("teams", 10),
        }
    provider = pbase.get_provider(args.provider, **kwargs)

    league = args.league or cfg.get("league", {}).get("league_id")
    if not league:
        refs = provider.discover()
        if not refs:
            sys.exit("No leagues visible with these credentials.")
        league = refs[0].league_id
        print(f"Using discovered league {league}")

    saved: list[dict] = []
    seasons = parse_seasons(args.seasons) if args.seasons else None
    if not seasons:
        refs = [r for r in provider.discover() if r.league_id == str(league)]
        seasons = list(refs[0].seasons) if refs and refs[0].seasons else [args.season or 2026]

    for season in seasons:
        try:
            bundle = provider.fetch_season(str(league), season)
        except pbase.AuthError as exc:
            sys.exit(f"Auth failed: {exc}")
        except pbase.ProviderError as exc:
            print(f"  skip {season}: {exc}")
            continue
        counts = store.save(bundle)
        saved.append({"season": season, "summary": bundle.summary(),
                      "landed": counts["landed"]})
        if not args.json:
            print(f"  saved {bundle.summary()}")
    store.close()
    if args.json:
        print(json.dumps({"league_id": str(league), "provider": args.provider,
                          "saved": saved}, indent=2))
    if not saved:
        sys.exit(doc.EXIT_NODATA)


def cmd_adp_load(args, cfg) -> None:
    """Load an ADP table so the reach analysis can run.

    CSV needs player_id and rank columns. The player_id must match whatever
    the provider uses, which is why this is a separate explicit step rather
    than something guessed during ingest.
    """
    store = Store(args.db)
    rows = []
    with open(args.csv, newline="", encoding="utf-8") as fh:
        for rec in csv.DictReader(fh):
            rows.append((args.season, args.provider, rec["player_id"],
                         rec.get("source", "consensus"), float(rec["rank"])))
    with store.tx() as c:
        c.executemany("INSERT OR REPLACE INTO adp VALUES (?,?,?,?,?)", rows)
    print(f"Loaded {len(rows)} ADP rows for {args.season}.")
    store.close()


def cmd_draft_watch(args, cfg) -> None:
    """Poll a live draft board and print each new pick as it lands.

    Runs in the terminal rather than the browser on purpose: the pick feed
    needs your ESPN session cookie, and a published page cannot hold one.
    `--once` reads a single snapshot; otherwise it loops every --interval
    seconds until the draft completes or you interrupt it.
    """
    provider = pbase.get_provider(args.provider)
    if not hasattr(provider, "draft_state"):
        sys.exit(f"{args.provider} has no live draft feed")

    league = args.league or cfg.get("league", {}).get("league_id")
    if not league:
        sys.exit("No league. Pass --league or set one in config/league.toml.")
    season = args.season or 2026

    names = _player_names(args.db)
    seen: set[int] = set()
    out = pathlib.Path(args.out) if args.out else None

    while True:
        try:
            state = provider.draft_state(str(league), season)
        except pbase.AuthError as exc:
            sys.exit(f"Auth failed: {exc}")
        except pbase.ProviderError as exc:
            print(f"  poll failed: {exc}", file=sys.stderr)
            state = None

        if state:
            fresh = [p for p in state["picks"] if p["overall"] not in seen]
            for pick in fresh:
                seen.add(pick["overall"])
                pick["name"] = names.get(pick["player_id"], pick["player_id"])
            if out:
                out.write_text(json.dumps(state, indent=2))
            if args.json:
                print(json.dumps({"drafted": state["drafted"],
                                  "total": len(state["picks"]),
                                  "new": fresh}, indent=2), flush=True)
            else:
                for pick in fresh:
                    print(f"  #{pick['overall']:>3} R{pick['round']:<2} "
                          f"{pick['team'][:22]:<23} {pick['name']}", flush=True)
            if args.once or state["drafted"]:
                if state["drafted"] and not args.once:
                    print("Draft complete.")
                break
        elif args.once:
            break
        time.sleep(max(args.interval, 5))


def _player_names(db: str) -> dict[str, str]:
    """Names for pick ids, from whatever the local database already knows."""
    try:
        store = Store(db)
        rows = store.q("SELECT player_id, name FROM player WHERE provider='espn'", ())
        store.close()
        return {r["player_id"]: r["name"] for r in rows}
    except Exception:
        return {}


def cmd_analyze(args, cfg) -> None:
    store = Store(args.db)
    provider, league = _scope(store, cfg, args)
    results = analytics.run_all(store, provider, league)
    store.close()
    payload = {
        "provider": provider, "league_id": league,
        "analyses": [
            {"key": r.key, "title": r.title, "headline": r.headline,
             "columns": r.columns, "rows": r.rows,
             "caveat": r.caveat, "note": r.note, "empty": r.empty}
            for r in results
        ],
    }
    emit(args, payload, report.render_text(results))


def cmd_report(args, cfg) -> None:
    store = Store(args.db)
    provider, league = _scope(store, cfg, args)
    rows = store.q(
        "SELECT season, name FROM league WHERE provider=? AND league_id=?",
        (provider, league),
    )
    meta = {
        "provider": provider,
        "league_id": league,
        "league_name": next((r["name"] for r in rows if r["name"]), "League analytics"),
        "seasons": [r["season"] for r in rows],
    }
    results = analytics.run_all(store, provider, league)
    path = report.render(results, meta, args.out)
    print(f"Wrote {path}")
    store.close()


def cmd_draft_report(args, cfg) -> None:
    """Write the standalone draft page for any league in the database.

    Nothing about it is specific to one league: point it at a provider and a
    league id you have pulled and it renders that league's draft.
    """
    store = Store(args.db)
    provider, league = _scope(store, cfg, args)

    me = args.me
    if not me:
        # Match the signed-in owner to their team, so "you" is highlighted
        # without anyone having to look up a numeric team id.
        swid = os.environ.get("ESPN_SWID", "")
        if swid:
            for r in store.q(
                "SELECT season, team_id, owner FROM manager "
                "WHERE provider=? AND league_id=?", (provider, league)
            ):
                if (r["owner"] or "").upper().strip("{}") == swid.upper().strip("{}"):
                    me = r["team_id"]
    try:
        payload = report.draft_report_payload(
            store, provider, league, season=args.season, me=me)
    except ValueError as exc:
        store.close()
        sys.exit(str(exc))
    path = report.render_draft_report(payload, args.out)
    store.close()

    if args.json:
        print(json.dumps({"out": str(path), "league": league, "season": payload["season"],
                          "picks": payload["pickCount"], "teams": payload["teamCount"],
                          "you": me, "adp_rows": payload["adpRows"]}, indent=2))
    else:
        note = "" if payload["adpRows"] else "  (no ADP loaded - reach columns will be empty)"
        print(f"Wrote {path}  {payload['pickCount']} picks, "
              f"{payload['teamCount']} teams, {payload['season']}{note}")


def cmd_serve(args, cfg) -> None:
    """Run the auto-syncing draft board on localhost.

    The published page cannot poll ESPN; this process can, because it holds the
    cookie. Bound to 127.0.0.1 so nothing is exposed off the machine.
    """
    from . import serve as srv

    provider = pbase.get_provider(args.provider)
    if not hasattr(provider, "draft_state"):
        sys.exit(f"{args.provider} has no live draft feed")
    league = args.league or cfg.get("league", {}).get("league_id")
    if not league:
        sys.exit("No league. Pass --league or set one in config/league.toml.")
    adp = args.adp
    if not pathlib.Path(adp).exists():
        sys.exit(f"No ADP file at {adp}. Point --adp at a CSV of player_id,name,pos,rank.")
    try:
        srv.run(provider, str(league), args.season or 2026, adp,
                port=args.port, poll=args.interval, skip_news=args.no_news,
                manual=args.manual, db=args.db)
    except pbase.AuthError as exc:
        sys.exit(f"Auth failed: {exc}")


def cmd_api(args, cfg) -> None:
    """Read-only JSON API over the database, for second-screen clients.

    The counterpart to `serve`. That one holds a cookie and polls ESPN, so it
    stays on loopback. This one calls no provider and holds no credential, so
    it can bind to the LAN and let a TV, a headset or another browser read the
    same league history.
    """
    from . import api as apisrv

    apisrv.run(db=args.db, host=args.host, port=args.port,
               allow_ai=not getattr(args, "no_ai", False))


def cmd_replay(args, cfg) -> None:
    """Replay a finished game through the real live tier.

    Writes the two files `live.EspnLiveSource._fetch` already reads, so the
    board and the API see a game in progress without a line of the live tier
    changing. Nothing here talks to a league, so it needs no credential and no
    database.
    """
    from . import replay as rp

    out = pathlib.Path(args.out)
    quiet = getattr(args, "json", False)
    if not quiet:
        # Printed before the loop, not after it. A replay at 60x runs for a
        # minute and a daemon runs until the game ends, so a notice that only
        # appears on exit is a notice nobody reads while deciding whether to
        # trust the numbers on their screen.
        print(f"Replaying event {args.game} into {out}")
        print(f"\nBOX SCORE: {rp.BOXSCORE_NOTE}")
        print(f"\nPoint a reader at it with:\n  {rp.run_hint(out)}\n")
    info = rp.run(args.game, out, speed=args.speed, at=args.at,
                  do_capture=args.capture, start=args.start,
                  interval=args.interval,
                  log=(lambda *a: None) if quiet else print)
    emit(args, info, f"\n{info['length']}s of game clock, "
                     f"{info['frames']} frame(s) written to {info['out']}")


def _week_range(args) -> list[int]:
    """Which weeks `projections sleeper` should fetch.

    A range rather than a single week because a source loaded for one week and
    compared against a source loaded for seventeen is not a comparison, and
    `projection_accuracy` says so in its own caveat.
    """
    if args.weeks:
        lo, _, hi = args.weeks.partition("-")
        try:
            return list(range(int(lo), int(hi or lo) + 1))
        except ValueError:
            sys.exit(f"--weeks wants a range like 1-14, got {args.weeks!r}")
    return [args.week or 1]


def cmd_projections(args, cfg) -> None:
    """Record projections so they can be scored against what happened."""
    from . import projections as pj

    store = Store(args.db)
    try:
        if args.action == "seed":
            out = pj.seed_espn(store, args.season)
            human = f"Recorded {out['rows']} ESPN projections."
        elif args.action == "sleeper":
            # Sleeper's numbers are fetched here rather than by `api`, which
            # calls no provider by design. The CLI writes rows; the API only
            # ever reads them.
            season = args.season or 2026
            weeks = _week_range(args)
            fmt = args.format or pj.scoring_format(cfg)
            loaded = [pj.load_sleeper(store, season, w, fmt=fmt,
                                      refresh=bool(args.refresh)) for w in weeks]
            out = {"loaded": loaded}
            human = "\n".join(
                f"  sleeper {d['season']} w{d['week']} ({d.get('format', '')}): "
                f"{d['rows']} of {d.get('offered', 0)} matched onto "
                f"{d.get('pool', 0)} stored players "
                f"[{', '.join(f'{k} {v}' for k, v in sorted((d.get('matched') or {}).items()))}]"
                for d in loaded)
        elif args.action == "sources":
            # The catalogue, not just the loaded list: a source that is absent
            # because nobody has a key for it is a different fact from a source
            # that is absent because nobody ran the loader, and a bare list of
            # strings cannot tell them apart.
            cat = pj.catalog(store, args.season, args.week)
            out = {"sources": cat}
            human = "\n".join(
                f"  {c['label']:<13} {'loaded' if c['loaded'] else c['status']:<8}"
                + (f" {c['rows']} rows over {c['weeks']} week(s)" if c["loaded"]
                   else (f" needs {c['needs']}" if c["needs"] else " nothing loaded"))
                for c in cat)
        elif args.action == "load-dir":
            if not args.dir:
                sys.exit("Pass --dir with a folder of <source>_<season>_w<week>.csv")
            loaded = pj.load_dir(store, args.dir)
            out = {"loaded": loaded}
            human = "\n".join(
                f"  {d['source']} {d['season']} w{d['week']}: {d['rows']} rows"
                + (f", {d['unmatched_count']} unmatched" if d["unmatched_count"] else "")
                for d in loaded) or "  nothing matched <source>_<season>_w<week>.csv"
        else:                                    # load
            for flag, val in (("--csv", args.csv), ("--source", args.source),
                              ("--season", args.season), ("--week", args.week)):
                if not val:
                    sys.exit(f"{flag} is required for `projections load`")
            out = pj.load_csv(store, args.csv, args.source, args.season, args.week)
            human = (f"Loaded {out['rows']} projections for {out['source']} "
                     f"{out['season']} week {out['week']}."
                     + (f" {out['unmatched_count']} unmatched: "
                        f"{', '.join(out['unmatched'][:5])}"
                        if out["unmatched_count"] else ""))
    finally:
        store.close()
    emit(args, out, human)


def _current_week(store, season: int | None) -> int:
    """The week `daily` should fetch projections for.

    Read from the database rather than from a calendar: `daily` may be catching
    up on a Tuesday for a Sunday already pulled, and a clock would fetch a week
    nothing is stored under. `projections.current_week` owns the rule.
    """
    from . import projections as pj
    return pj.current_week(store, season or 2026) or 1


def cmd_daily(args, cfg) -> None:
    """One cron-able pass: refresh the week, record projections, score them.

    Built to be run on a timer and read by a machine. Every step reports
    whether it ran, so a partial failure is visible rather than silent.
    """
    from . import projections as pj

    steps, ok = [], True
    if not args.no_pull:
        try:
            pull_args = argparse.Namespace(**vars(args))
            pull_args.seasons = args.seasons or str(args.season or 2026)
            pull_args.json = True
            import io
            import contextlib
            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                cmd_pull(pull_args, cfg)
            steps.append({"step": "pull", "ok": True})
        except SystemExit as exc:
            ok = False
            steps.append({"step": "pull", "ok": False, "detail": str(exc)})
        except Exception as exc:
            ok = False
            steps.append({"step": "pull", "ok": False, "detail": str(exc)})

    store = Store(args.db)
    try:
        seeded = pj.seed_espn(store, args.season)
        steps.append({"step": "seed_projections", "ok": True, "rows": seeded["rows"]})
        # Sleeper on the same timer as ESPN, because a second source loaded for
        # fewer weeks than the first is not comparable to it - see the caveat
        # on `projection_accuracy`. A failure here is recorded and does not
        # stop the pass: one source going quiet must not cost the other.
        try:
            slp = pj.load_sleeper(store, args.season or 2026,
                                  args.week or _current_week(store, args.season),
                                  fmt=pj.scoring_format(cfg))
            steps.append({"step": "sleeper_projections", "ok": True,
                          "rows": slp["rows"], "matched": slp["matched"]})
        except Exception as exc:
            steps.append({"step": "sleeper_projections", "ok": False,
                          "detail": str(exc)})
        provider, league = _scope(store, cfg, args)
        res = analytics.ANALYSES["projection_accuracy"](store, provider, league)
        steps.append({"step": "score", "ok": not res.empty,
                      "sources": len(res.rows)})
    finally:
        store.close()

    payload = {"ok": ok, "steps": steps, "provider": provider, "league_id": league,
               "accuracy": {"key": res.key, "title": res.title,
                            "headline": res.headline, "columns": res.columns,
                            "rows": res.rows, "caveat": res.caveat,
                            "empty": res.empty}}
    human = "\n".join(
        [f"  {s['step']}: {'ok' if s['ok'] else 'FAILED'}"
         + (f" ({s.get('rows', s.get('sources'))})"
            if s.get("rows") is not None or s.get("sources") is not None else "")
         for s in steps]
        + ["", "  " + (res.headline or "No projection sources scored yet."),
           "  " + res.caveat])
    emit(args, payload, human)


def cmd_leagues(args, cfg) -> None:
    """The leagues this install follows. Stored outside the repo, so it lasts."""
    from . import leagues as lg
    if args.add:
        prov, _, lid = args.add.partition(":")
        if not lid:
            sys.exit("use --add provider:league_id, e.g. --add espn:289515778")
        entries = lg.add(prov, lid, args.label or "", tuple(args.also or []))
    elif args.remove:
        entries = lg.remove(args.remove)
    else:
        entries = lg.load()
    if args.json:
        print(json.dumps(entries, indent=2))
    elif not entries:
        print("No leagues yet. Add one:\n"
              "  python3 -m fantasyedge leagues --add espn:289515778 --label BAWA")
    else:
        for e in entries:
            extra = f"  (+history {', '.join(e['also'])})" if e.get("also") else ""
            print(f"  {e['provider']:<8} {e['league_id']:<12} {e.get('label','')}{extra}")


def cmd_sync(args, cfg) -> None:
    """Refresh every followed league. One command, no re-adding anything."""
    from . import leagues as lg
    entries = lg.load()
    if not entries:
        sys.exit("No leagues followed yet. Run `leagues --add provider:league_id` first.")
    store = Store(args.db)
    done = []
    for e in entries:
        ids = [e["league_id"], *e.get("also", [])]
        for lid in ids:
            try:
                provider = pbase.get_provider(e["provider"])
            except Exception as exc:
                print(f"  {e['provider']}: {exc}")
                break
            seasons = parse_seasons(args.seasons) if args.seasons else [args.season or 2026]
            for season in seasons:
                try:
                    bundle = provider.fetch_season(str(lid), season)
                except pbase.AuthError as exc:
                    print(f"  {e['provider']}:{lid} {season}: auth failed - {exc}")
                    continue
                except pbase.ProviderError as exc:
                    print(f"  {e['provider']}:{lid} {season}: {exc}")
                    continue
                store.save(bundle)
                done.append(f"{e['provider']}:{lid} {season}")
                print(f"  saved {bundle.summary()}")
    store.close()
    if args.json:
        print(json.dumps({"synced": done}, indent=2))


def cmd_status(args, cfg) -> None:
    store = Store(args.db)
    rows = [dict(r) for r in store.seasons()]
    store.close()
    human = "\n".join(
        f"{r['provider']:7} {r['league_id']:12} {r['season']}  "
        f"{r['team_count']} teams  {r['name']}" for r in rows
    ) or "Empty. Run `pull` first."
    emit(args, {"seasons": rows, "count": len(rows)}, human)
    if not rows:
        sys.exit(doc.EXIT_NODATA)


# ───────────────────────────── wiring ────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="fantasyedge", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--db", default="data/fantasy.db")
    p.add_argument("--config", default=str(DEFAULT_CONFIG))
    p.add_argument("--json", action="store_true",
                   help="machine-readable output for agents and scripts")
    sub = p.add_subparsers(dest="cmd", required=True)

    def jsonify(sp):
        """--json must work before OR after the subcommand.

        Argparse normally forces global flags to precede the subcommand, which
        is precisely the mistake an agent makes first. SUPPRESS means the
        subparser only sets the attribute when the flag is actually present,
        so the global value survives when it is not.
        """
        sp.add_argument("--json", action="store_true", default=argparse.SUPPRESS,
                        help="machine-readable output")
        return sp

    def common(sp):
        sp.add_argument("--provider", choices=pbase.known_providers())
        sp.add_argument("--league")
        return jsonify(sp)

    su = sub.add_parser("setup", help="write config/league.toml from flags")
    su.add_argument("--provider", default="espn", choices=pbase.known_providers())
    su.add_argument("--league"); su.add_argument("--teams", type=int)
    jsonify(su); su.set_defaults(fn=cmd_setup)

    dr = sub.add_parser("doctor", help="diagnose setup and print the next command")
    jsonify(dr); dr.set_defaults(fn=cmd_doctor)

    a = sub.add_parser("auth", help="one-time OAuth for Yahoo")
    a.add_argument("--provider", default="yahoo", choices=pbase.known_providers())
    a.add_argument("--url", action="store_true", help="print authorize URL and exit")
    a.add_argument("--code", help="authorization code, completes the exchange")
    a.add_argument("--local", action="store_true",
                   help="open a browser and catch the code on 127.0.0.1 "
                        "(needs a loopback redirect URI registered with the provider)")
    jsonify(a); a.set_defaults(fn=cmd_auth)

    d = common(sub.add_parser("discover", help="list leagues and seasons"))
    d.add_argument("--draft"); d.add_argument("--standings")
    d.set_defaults(fn=cmd_discover)

    pl = common(sub.add_parser("pull", help="ingest league-seasons"))
    pl.add_argument("--seasons", help="2024, 2022-2026, or 2022,2024")
    pl.add_argument("--season", type=int)
    pl.add_argument("--draft"); pl.add_argument("--standings")
    pl.add_argument("--teams", type=int)
    pl.set_defaults(fn=cmd_pull)

    ad = sub.add_parser("adp-load", help="load ADP for the reach analysis")
    ad.add_argument("--season", type=int, required=True)
    ad.add_argument("--provider", default="espn")
    ad.add_argument("--csv", required=True)
    jsonify(ad); ad.set_defaults(fn=cmd_adp_load)

    dw = common(sub.add_parser("draft-watch", help="follow a live draft board"))
    dw.add_argument("--season", type=int)
    dw.add_argument("--interval", type=int, default=30,
                    help="seconds between polls (default 30, minimum 5)")
    dw.add_argument("--once", action="store_true", help="one snapshot, then exit")
    dw.add_argument("--out", help="also write the full board to this JSON file")
    dw.set_defaults(fn=cmd_draft_watch)

    an = common(sub.add_parser("analyze", help="print analyses to the terminal"))
    an.set_defaults(fn=cmd_analyze)

    rp = common(sub.add_parser("report", help="write the HTML report"))
    rp.add_argument("--out", default="report.html")
    rp.set_defaults(fn=cmd_report)

    dp = common(sub.add_parser("draft-report", help="standalone draft page for any league"))
    dp.add_argument("--season", type=int, help="defaults to the newest drafted season")
    dp.add_argument("--me", help="your team id, to highlight it (auto-detected from ESPN_SWID)")
    dp.add_argument("--out", default="draft-report.html")
    dp.set_defaults(fn=cmd_draft_report)

    sv = common(sub.add_parser("serve", help="auto-syncing draft board on localhost"))
    sv.add_argument("--season", type=int)
    sv.add_argument("--port", type=int, default=8765)
    sv.add_argument("--interval", type=int, default=30, help="seconds between polls")
    sv.add_argument("--adp", default="data/adp/espn_2026.csv")
    sv.add_argument("--no-news", action="store_true", help="skip the news fetch")
    sv.add_argument("--manual", help="file of player names, one per pick, used "
                                     "while ESPN reports a live draft as empty")
    sv.set_defaults(fn=cmd_serve)

    ap = sub.add_parser("api", help="read-only JSON API over the database")
    ap.add_argument("--host", default="127.0.0.1",
                    help="0.0.0.0 to let other devices on your network read it")
    ap.add_argument("--port", type=int, default=8770)
    ap.add_argument("--no-ai", action="store_true",
                    help="refuse POST /api/intel/narrate and report every model "
                         "provider as unconfigured. For the headset build, where "
                         "there is nobody to type a key and the computed brief is "
                         "the whole product anyway")
    jsonify(ap); ap.set_defaults(fn=cmd_api)

    rpl = sub.add_parser("replay", help="replay a finished NFL game as if it were live")
    rpl.add_argument("--game", required=True, help="ESPN event id, e.g. 401872656")
    rpl.add_argument("--out", default="data/replay",
                     help="directory the frames are written to")
    rpl.add_argument("--speed", type=float, default=60.0,
                     help="game seconds per wall second (default 60: a game in a minute)")
    rpl.add_argument("--at", type=int,
                     help="write one frozen frame at this many game seconds, then exit")
    rpl.add_argument("--start", type=int, default=0, help="game second to start from")
    rpl.add_argument("--interval", type=float, default=1.0,
                     help="wall seconds between frames")
    rpl.add_argument("--capture", action="store_true",
                     help="re-download the game from ESPN before replaying")
    jsonify(rpl); rpl.set_defaults(fn=cmd_replay)

    pj = common(sub.add_parser("projections",
                               help="record projections so they can be scored"))
    pj.add_argument("action",
                    choices=["seed", "sleeper", "load", "load-dir", "sources"])
    pj.add_argument("--csv"); pj.add_argument("--dir")
    pj.add_argument("--source", help="espn, nfl, cbs, fantasypros, ...")
    pj.add_argument("--season", type=int); pj.add_argument("--week", type=int)
    pj.add_argument("--weeks", help="a range for `sleeper`, e.g. 1-14")
    pj.add_argument("--format", choices=["ppr", "half_ppr", "std"],
                    help="which of Sleeper's three columns; default follows "
                         "config/league.toml's reception value")
    pj.add_argument("--refresh", action="store_true",
                    help="ignore the on-disk cache and refetch")
    pj.set_defaults(fn=cmd_projections)

    dy = common(sub.add_parser("daily",
                               help="cron-able: refresh, record projections, score them"))
    dy.add_argument("--season", type=int, default=2026)
    dy.add_argument("--seasons", help="override the range passed to pull")
    dy.add_argument("--no-pull", action="store_true", help="skip the network step")
    dy.add_argument("--week", type=int,
                    help="which week to fetch Sleeper for; default is the "
                         "latest week the database has rosters for")
    dy.set_defaults(fn=cmd_daily)

    lgp = sub.add_parser("leagues", help="list or change the leagues you follow")
    lgp.add_argument("--add", help="provider:league_id")
    lgp.add_argument("--label")
    lgp.add_argument("--also", nargs="*", help="older league ids holding this league's history")
    lgp.add_argument("--remove")
    jsonify(lgp); lgp.set_defaults(fn=cmd_leagues)

    sy = common(sub.add_parser("sync", help="refresh every followed league"))
    sy.add_argument("--season", type=int)
    sy.add_argument("--seasons", help="2024, 2022-2026, or 2022,2024")
    sy.set_defaults(fn=cmd_sync)

    st = common(sub.add_parser("status", help="what is loaded"))
    st.set_defaults(fn=cmd_status)
    return p


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    if not hasattr(args, "json"):
        args.json = False
    cfg = load_config(pathlib.Path(args.config))
    args.fn(args, cfg)


if __name__ == "__main__":
    main()
